### 异常

Golang 没有结构化异常，使用 `panic` 抛出错误，`recover` 捕获错误。

异常使用场景简单描述： Go中可以抛出一个`panic`的异常，然后在`defer`中通过`recover`捕获这个异常，然后正常处理。

#### panic 和 recover

##### panic  惊恐

1. 内置函数
2. 假如函数F中书写了`panic`语句，会终止其后要执行的代码，在`panic`所在函数F内如果存在要执行的`defer`函数列表，按照defer的逆序执行(先进后出)
3. 返回函数F的调用者G，在G中，调用函数F语句之后的代码不会执行，假如函数G中存在要执行的`defer`函数列表，按照`defer`的逆序执行
4. 直到goroutine整个退出，并报告错误


##### recover 恢复

1. 内置函数
2. 用来控制一个 goroutine 的 panicking 行为，捕获 panic，从而影响应用的行为
3. 一般调用建议
   * 在defer函数中，通过`recever`来终止一个goroutine的panicking过程，从而恢复正常代码的执行
   * 可以获取通过panic传递的error


##### 注意:

1. 利用`recover`处理`panic`指令，`defer` 必须放在 `panic` 之前定义，另外 `recover` 只有在 `defer` 调用的函数中才有效。否则当`panic`时，`recover`无法捕获到`panic`，无法防止`panic`扩散。
2. `recover` 处理异常后，逻辑并不会恢复到 `panic` 那个点去，函数跑到 `defer` 之后的那个点。
3. 多个 `defer` 会形成 `defer` 栈，后定义的 `defer` 语句会被最先调用。

```go
package main

func main() {
    test()
}

func test() {
    defer func() {
        if err := recover(); err != nil {
            println(err.(string)) // 将 interface{} 转型为具体类型。
        }
    }()

    panic("panic error!")
}  

```